productName = "cloudflare-dns-gui"
version = "1.0.0"
identifier = "one.nwest.apps.cloudflare-dns-gui"

[build]
beforeDevCommand = "pnpm dev"
devUrl = "http://localhost:1420"
beforeBuildCommand = "pnpm build"
frontendDist = "../dist"

[[app.windows]]
title = "cloudflare-dns-gui"
width = 800
height = 600

[app.security]

[bundle]
active = true
targets = "all"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico",
]
