branches:
  - main
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/exec"
    - generateNotesCmd: version ${nextRelease.version} dry-run
      prepareCmd: version ${nextRelease.version}
  - - "@semantic-release/git"
    - assets:
      - CHANGELOG.md
      - package.json
      message: "chore: release ${nextRelease.version}\n\n${nextRelease.notes}"
  - "@semantic-release/github"
