branches:
  - main
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/exec"
    - prepareCmd: echo "$( jq --arg v ${nextRelease.version} '.version = $v' package.json )" > package.json
  - - "@semantic-release/git"
    - assets:
      - CHANGELOG.md
      - package.json
      message: "chore: release ${nextRelease.version}\n\n${nextRelease.notes}"
  - "@semantic-release/github"
