// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cloudflare tenet information.
 */
export type CloudflareTenant = { 
/**
 * The tenant identifier
 */
id: string | null, 
/**
 * The tenant name
 */
name: string | null, };