// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cloudflare serializes errors and messages the same way.
 *
 * - code: The error code. An integer >= 1000.
 * - message: A human-readable message.
 */
export type CloudflareMessage = { 
/**
 * The error or message code. An integer >= 1000.
 */
code: number, 
/**
 * A human-readable message.
 */
message: string, };