// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cloudflare zone owner information.
 */
export type CloudflareOwner = { 
/**
 * The owner ID.
 *
 * Example: `023e105f4ecef8ad9ca31a8372d0c353`
 */
id: string | null, 
/**
 * The name of the owner.
 *
 * Example: `Cloudflare, Inc.`
 */
name: string | null, 
/**
 * The type of the owner.
 *
 * Example: `organization`
 */
type: string, };