// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cloudflare account information.
 */
export type CloudflareAccount = { 
/**
 * The account identifier.
 */
id: string, 
/**
 * The account name.
 */
name: string, };