// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cloudflare API responses include result information sometimes.
 */
export type CloudflareResultInfo = { 
/**
 * The page number of the current page.
 */
page: number, 
/**
 * The number of items per page.
 */
per_page: number, 
/**
 * The total number of pages.
 */
total_pages: number, 
/**
 * The total number of items.
 */
count: number, 
/**
 * The total number of items that would be available without any filtering.
 */
total_count: number, };