// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cloudflare plan information.
 */
export type CloudflarePlan = { 
/**
 * The plan identifier
 */
id: string, 
/**
 * The plan name
 */
name: string, 
/**
 * The plan price
 */
price: number, 
/**
 * The plan currency
 */
currency: string, 
/**
 * The plan frequency
 */
frequency: string, 
/**
 * Is the plan a subscription?
 */
is_subscribed: boolean, 
/**
 * Can the plan be a subscription?
 */
can_subscribe: boolean, 
/**
 * The plan's legacy identifier
 */
legacy_id: string, 
/**
 * Does the plan have a legacy discount?
 */
legacy_discount: boolean, 
/**
 * Is the plan externally managed?
 */
externally_managed: boolean, };