// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cloudflare organization information.
 */
export type CloudflareOrganizationUserDetails = { 
/**
 * The organization identifier for the user
 */
id: string, 
/**
 * The organization name
 */
name: string, 
/**
 * The user's role in the organization
 */
status: string, 
/**
 * The organization permissions the user has
 */
permissions: Array<string>, 
/**
 * The organization's roles the user has
 */
roles: Array<string>, };