// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudflareAccount } from "./CloudflareAccount";
import type { CloudflareOwner } from "./CloudflareOwner";
import type { CloudflarePlan } from "./CloudflarePlan";
import type { CloudflareTenant } from "./CloudflareTenant";
import type { CloudflareTenantUnit } from "./CloudflareTenantUnit";

/**
 * Cloudflare endpoint response for List Zones.
 */
export type CloudflareListZonesResponse = { 
/**
 * The account the zone belongs to.
 */
account: CloudflareAccount, 
/**
 * The last time proof of ownership was detected and the zone was made active
 *
 * Example: `2014-01-02T00:01:00.12345Z`
 */
activated_on: string, 
/**
 * The time the zone was created
 *
 * Example: `2014-01-01T05:20:00.12345Z`
 */
created_on: string, 
/**
 * The interval (in seconds) from when development mode expires (positive integer)
 * or last expired (negative integer) for the domain. If development mode has never been enabled, this value is 0.
 */
development_mode: number, 
/**
 * The zone identifier
 *
 * This is a string <= 32 characters.
 *
 * Example: `023e105f4ecef8ad9ca31a8372d0c353`
 */
id: string, 
/**
 * When the zone was last modified
 *
 * Example: `2014-01-01T05:20:00.12345Z`
 */
modified_on: string, 
/**
 * The domain name. This is <= 253 characters.
 *
 * Example: `example.com`
 *
 * Match pattern: `^([a-zA-Z0-9][\-a-zA-Z0-9]*\.)+[\-a-zA-Z0-9]{2,20}$`
 */
name: string, 
/**
 * DNS host at the time of switching to Cloudflare. <= 50 characters.
 *
 * Example: `NameCheap`
 */
original_dnshost: string | null, 
/**
 * Original name servers before moving to Cloudflare Notes: Is this only available for full zones?
 *
 * Example: `["ns1.originaldnshost.com","ns2.originaldnshost.com"]`
 */
original_name_servers: Array<string> | null, 
/**
 * Registrar for the domain at the time of switching to Cloudflare. <= 50 characters.
 *
 * Example: `GoDaddy`
 */
original_registrar: string | null, 
/**
 * The owner of the zone.
 */
owner: CloudflareOwner, 
/**
 * An array of domains used for custom name servers. This is only available for Business and Enterprise plans.
 *
 * Example: `["ns1.example.com","ns2.example.com"]`
 */
vanity_name_servers: Array<string> | null, 
/**
 * What tenant the zone is in
 */
tenant: CloudflareTenant, 
/**
 * What tenant unit the zone is in
 */
tenant_unit: CloudflareTenantUnit, 
/**
 * What permissions are available on the zone
 */
permissions: Array<string>, 
/**
 * What plan the zone is on
 */
plan: CloudflarePlan, 
/**
 * The zone's status
 */
status: string, 
/**
 * Whether the zone is paused
 */
paused: boolean, };