// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cloudflare tenet unit information.
 */
export type CloudflareTenantUnit = { 
/**
 * The tenant unit identifier
 */
id: string | null, };