// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cloudflare zone metadata information.
 */
export type CloudflareZoneMetadata = { 
/**
 * The zone is only configured for CDN
 */
cdn_only: boolean, 
/**
 * Number of Custom Certificates the zone can have
 */
custom_certificate_quota: number, 
/**
 * The zone is only configured for DNS
 */
dns_only: boolean, 
/**
 * The zone is setup with Foundation DNS
 */
foundation_dns: boolean, 
/**
 * Number of Page Rules a zone can have
 */
page_rule_quota: number, 
/**
 * The zone has been flagged for phishing
 */
phishing_detected: boolean, 
/**
 * Not described in documentation, example value: `2`
 */
step: number, };