// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudflareOrganizationUserDetails } from "./CloudflareOrganizationUserDetails";

/**
 * Cloudflare endpoint response for Get User Details
 */
export type CloudflareUserDetailsResponse = { 
/**
 * The user's identifier
 *
 * Example: `023e105f4ecef8ad9ca31a8372d0c353`
 */
id: string, 
/**
 * The user's email address
 */
email: string, 
/**
 * The user's username
 */
username: string, 
/**
 * The user's first name
 */
first_name: string | null, 
/**
 * The user's last name
 */
last_name: string | null, 
/**
 * The user's telephone number
 */
telephone: string | null, 
/**
 * The user's country
 */
country: string | null, 
/**
 * The user's zipcode
 */
zipcode: string | null, 
/**
 * Does the user have TFA enabled?
 */
two_factor_authentication_enabled: boolean, 
/**
 * Is the user's TFA locked?
 */
two_factor_authentication_locked: boolean, 
/**
 * The user's created date
 *
 * Example: `2014-01-01T05:20:00.12345Z`
 */
created_on: string, 
/**
 * The user's modified date
 *
 * Example: `2014-01-01T05:20:00.12345Z`
 */
modified_on: string, 
/**
 * The user's organizations
 */
organizations: Array<CloudflareOrganizationUserDetails>, 
/**
 * Whether the user has pro zones
 */
has_pro_zones: boolean, 
/**
 * Whether the user has business zones
 */
has_business_zones: boolean, 
/**
 * Whether the user has enterprise zones
 */
has_enterprise_zones: boolean, 
/**
 * Whether the user's account is suspended
 */
suspended: boolean, 
/**
 * The user's beta entitlements
 */
betas: Array<string>, };