// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Short details about the user, for display in the UI.
 */
export type CustomUserDetails = { 
/**
 * The user ID.
 */
id: string, 
/**
 * The email address of the user.
 */
email: string, 
/**
 * Whether the user is suspended.
 */
suspended: boolean, 
/**
 * The organizations the user is a member of (just the names).
 */
organizations: Array<string>, };