// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Meta } from "./Meta";

/**
 * A DNS record response
 */
export type DNSRecord = { 
/**
 * The stored DNS record.
 * For A or AAAA records, this is the IP address.
 * For most others, this is the content of the record (string)
 */
content: string, 
/**
 * The DNS record identifier. @ for root record
 */
name: string, 
/**
 * Whether the record is proxied by Cloudflare
 */
proxied: boolean | null, 
/**
 * The record type (A, AAAA, CNAME, etc.)
 */
type: string, 
/**
 * Comments or notes about the DNS record. This field has no effect on DNS responses.
 */
comment: string | null, 
/**
 * When the record was created. Example: `2014-01-01T05:20:00.12345Z`
 */
created_on: string, 
/**
 * Identifier for the record (used with the API)
 */
id: string, 
/**
 * Whether this record can be modified/deleted (true means it's managed by Cloudflare)
 */
locked: boolean, 
/**
 * Extra Cloudflare-specific information about the record.
 */
meta: Meta, 
/**
 * When the record was last modified. Example: `2014-01-01T05:20:00.12345Z`
 */
modified_on: string | null, 
/**
 * Whether the record can be proxied by Cloudflare or not
 */
proxiable: boolean, 
/**
 * Custom tags for the record
 */
tags: Array<string>, 
/**
 * Time to live for the record. To signify `auto ttl`, set this to `1`. Valid values: 60 - 86400,0,1
 */
ttl: number, 
/**
 * The zone identifier
 */
zone_id: string | null, 
/**
 * The zone name
 */
zone_name: string, };