// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Extra Cloudflare-specific information about the record.
 */
export type Meta = { 
/**
 * Whether the record was automatically added by Cloudflare during initial setup
 */
auto_added: boolean | null, 
/**
 * The source of the record. This is typically the name of the service that the record was imported from.
 */
source: string | null, };